export const languages = [
  // Popular High-level
  { name: "Python", slug: "python", id: 71 },
  { name: "JavaScript", slug: "javascript", id: 63 },
  { name: "TypeScript", slug: "typescript", id: 74 },
  { name: "Java", slug: "java", id: 62 },
  { name: "C", slug: "c", id: 50 },
  { name: "C++", slug: "cpp", id: 54 },
  { name: "C#", slug: "csharp", id: 51 },
  { name: "Go", slug: "go", id: 60 },
  { name: "Rust", slug: "rust", id: 73 },
  { name: "Kotlin", slug: "kotlin", id: 78 },
  { name: "Swift", slug: "swift", id: 83 },
  { name: "PHP", slug: "php", id: 68 },
  { name: "Ruby", slug: "ruby", id: 72 },
  { name: "Perl", slug: "perl", id: 79 },
  { name: "R", slug: "r", id: 80 },
  { name: "Scala", slug: "scala", id: 81 },
  { name: "Lua", slug: "lua", id: 82 },
  { name: "Haskell", slug: "haskell", id: 61 },
  { name: "Shell Script", slug: "bash", id: 46 },
  { name: "Objective-C", slug: "objective_c", id: 84 },
  { name: "Dart", slug: "dart", id: 85 },
  { name: "SQL", slug: "sql", id: 86 },
  { name: "Elixir", slug: "elixir", id: 87 },
  { name: "Assembly", slug: "assembly", id: 45 },
];
//*  ------------------------ Future work in-sha-allah
// export const databases = [
//    Relational
//   { name: "MySQL", type: "Relational" },
//   { name: "PostgreSQL", type: "Relational" },
//   { name: "SQLite", type: "Relational" },
//   { name: "MariaDB", type: "Relational" },
//   { name: "Oracle Database", type: "Relational" },
//   { name: "Microsoft SQL Server", type: "Relational" },

//    NoSQL
//   { name: "MongoDB", type: "Document (NoSQL)" },
//   { name: "Cassandra", type: "Wide-Column (NoSQL)" },
//   { name: "CouchDB", type: "Document (NoSQL)" },
//   { name: "Firebase Realtime Database", type: "Realtime (NoSQL)" },
//   { name: "Redis", type: "Key-Value (In-memory)" },
//   { name: "Elasticsearch", type: "Search Engine / NoSQL" },
//   { name: "DynamoDB", type: "Key-Value / NoSQL" },
//   { name: "Neo4j", type: "Graph Database" },
//   { name: "InfluxDB", type: "Time-Series Database" },
//   { name: "Supabase", type: "PostgreSQL-based" },
// ];

// export const runtimesAndFrameworks = [
//   { name: "Node.js", type: "JavaScript Runtime" },
//   { name: "Deno", type: "JavaScript/TypeScript Runtime" },
//   { name: "Bun", type: "JavaScript Runtime" },
//   { name: "React", type: "Frontend Library" },
//   { name: "Next.js", type: "React Framework" },
//   { name: "Angular", type: "Frontend Framework" },
//   { name: "Vue.js", type: "Frontend Framework" },
//   { name: "Express.js", type: "Backend Framework" },
//   { name: "Django", type: "Python Framework" },
//   { name: "Flask", type: "Python Framework" },
//   { name: "Spring Boot", type: "Java Framework" },
//   { name: "Laravel", type: "PHP Framework" },
//   { name: "Ruby on Rails", type: "Ruby Framework" },
//   { name: "ASP.NET Core", type: "C# Framework" },
//   { name: "FastAPI", type: "Python Framework" },
//   { name: "TensorFlow", type: "Machine Learning Framework" },
//   { name: "PyTorch", type: "Machine Learning Framework" },
//   { name: "Keras", type: "Deep Learning Library" },
// ];
